name: pinme
description: "Location-based reminder app with geofencing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  
  go_router: ^14.2.7
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  geofence_service: ^6.0.0+1
  geolocator: ^12.0.0
  
  flutter_local_notifications: ^17.2.3
  
  workmanager: ^0.5.2
  
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  google_polyline_algorithm: ^3.1.0
  
  permission_handler: ^11.3.1
  
  uuid: ^4.5.1
  intl: ^0.19.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  
  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/sample_data/
